### ISSUE TITLE
printbutton is only shown in default shop, not in other shops

### ISSUE THREAD

**Issue by brrrm** [eltrino/Compatibility#1]
Hi,

I installed your printorder 1.1 extension in Magento 1.9.0.1 and it's working fine in our default store. But not in any other store. The template is being loaded but the if-statement 
<?php if ($this->getCanPrintOrder()) :?> 
in printorder.phtml is always false.

What could be the cause of this?

**Comment by northdakota** [comment]
This issue was moved to eltrino/PrintOrder#1

**Comment by northdakota** [comment]
This issue was moved to eltrino/PrintOrder#2
